- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-071f5060587c84be7
    zone_id: Z02150843EPAKGJ2WU2UT
    domain_name: daws86s.fun
    instance:
    - mangodb
  tasks:
  - name: create ec2 instance
  amezon.aws.ec2_instance:
    name: "{{item}}"
    instance_type: t3.micro
    security_group: "{{sg_id}}"
    image_id: "{{ami_id}}"
    tags:
      name: "{{item}}"
  loop: "{{instance}}"
  register: ec2_output

- name: print the ec2_output
  ansible.builtin.debug:
    msg: "{{ec2_output}}"